### ISSUE TITLE
Custom Controls/Plugins need to be packaged separately as part of the deployment

### ISSUE THREAD

**Issue by blueelvis** [carltoncolter/dyn-req-mgmt#3]
I already read the README present in the `CustomControls` folder but I think that it would make much more sense if we can just get a single consolidated ZIP file which deploys the pre-requisites and the main solution.

I found the following issues -
1. The `RichTextBoxControl` solution is not packaged up during the build Even running spkl runs the task runner in the `SolutionPackage` folder.
2. The plugin assemblies still do not get bundled up despite taking the latest solution when running SolutionPackager. I tried running with the exact parameters which you provided in the repo but I am seeing the following -

```
Following root components are not defined in customizations:
  Type='PluginAssembly', Id (or schema name)='{fdf355a2-a148-e811-a94d-000d3a3ac063}'.

Following root components are not defined in customizations:
  Type='PluginAssembly', Id (or schema name)='{fdf355a2-a148-e811-a94d-000d3a3ac063}'.

CrmSvcUtil Runtime = 00:00:11.8581962
```

Please do note that if I run spkl, the plugin assemblies are being bundled properly. Following is the command which I am running in the `SolutionPackage` folder - `C:\Dynamics365SDK\Sdk\Bin\SolutionPackager.exe /actio
n:pack /zipfile:"FedBizApps_Request_03.zip" /folder:"package" /packagetype:unmanaged /errorlevel:Verbose /map:"map.xml"`

Thanks,
Pranav

**Comment by carltoncolter** [comment]
So it did import or did not import?

The custom control does have to be installed prior.  When I installed the solution the last time, I used Package Deployer.  I have it setup to install the custom control solution and then the FedBizApps Request Management solution.  If it is not working for you, can you share the version information for the org?  If it is different than mine I will delete my instance and recreate one to see if I can match the version and attempt to reinstall from scratch.

**Comment by carltoncolter** [comment]
I updated the link accordingly.
