### ISSUE TITLE
Could you please explain the flow?

### ISSUE THREAD

**Issue by blueelvis** [carltoncolter/dyn-req-mgmt#4]
Hi Carlton,

Could you please explain the flow which is supposed to be happening when requests are created and which roles would have access? If there are 3 users with the following roles, would they be able to complete/walkthrough the entire flow?

1. Approval User
2. Approval Configurator
3. Approval Administrator

Thanks,
Pranav

**Comment by carltoncolter** [comment]
Given the direction of the Microsoft [Flow Approvals](https://flow.microsoft.com/en-us/connectors/shared_approvals/approvals/), I suggest looking into it. There were some reasons why I built it out inside CRM, such as flows not being part of a solution and the approval process not facilitating multiple labels for approve and deny, as well as the inability to add additional response options, such as abstain, or acknowledge receipt.

The approval system inside of the requrest management system is really designed to handle multiple types of actions.  The Approval Configurator is for users setting up the Approval Regarding Configuration, Approval Action Groups and Templates. Approval Administrators can create an approval action and approval request across the organization, where as an approval user can only create actions for themselves. An Approval Admin still needs to have the User Role to function properly.
