### ISSUE TITLE
Issues with Processes/Workflows/Actions

### ISSUE THREAD

**Issue by blueelvis** [carltoncolter/dyn-req-mgmt#5]
After importing the solution, I found a couple of issues which were not notified during import but were causing issues while going through the flow of a user creating a request for approval.

Following are the processes/workflows which have issues after importing and are in `Draft` state.

### 1. Assignment Notification: Request
In this, the currency is set to US Dollar. This doesn't work on instances with currencies other than the dollar.
Error - 
![image](https://user-images.githubusercontent.com/6985763/44090639-844f92e0-9fe8-11e8-98d2-a73c518535f3.png)

 Can this be fixed so that the task uses the primary currency of the organization?

### 2. Assignment Notification: Task
Same as (1)

### 3. Initiate Public Affairs Correspondence Approval Request
I am seeing an error that `This process includes an invalid reference`. I made sure that the entity exists as well.
Error - 
 ![image](https://user-images.githubusercontent.com/6985763/44090771-f01ad80e-9fe8-11e8-8ad7-74a9abbba839.png)

### 4. Request Department Approval
Same issue as (3)

### 5. Request Final Review
Same issue as (3)

Because of the above issues, if I try to create a new request for approval and then follow along the BPF, it doesn't work as expected because quite a few fields don't get populated or approvals are not generated accordingly.

Thanks,
Pranav

**Comment by carltoncolter** [comment]
This is an issue with the currency not being set on the user or in the system.  Both of those should be set prior to importing the solution.
